version: '3.4'
services:
  db:
    image: mysql-todolist
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: todolist
    ports:
      - "3308:3306"
    networks:
      - todolist-network
    
  backend:
    image: backend-todolist
    restart: always
    build: ./backend/organizador
    working_dir: /backend/organizador
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./backend/organizador:/backend/organizador
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - todolist-network
networks:
    todolist-network:
        driver: bridge